-- Columns/defaults from the user's read-only Supabase diagnostic, 2026-09-29.
create table public.products (
  id bigint generated by default as identity not null primary key,
  title text not null,
  description text,
  price numeric(10,2) not null,
  promotional_price numeric(10,2),
  stock integer default 0,
  images jsonb default '[]'::jsonb,
  video_url text,
  category text,
  tags text[],
  variants jsonb default '[]'::jsonb,
  seo_title text,
  seo_description text,
  is_active boolean default true,
  created_at timestamp without time zone default now(),
  sale_mode text default 'normal'::text not null,
  is_kit boolean default false,
  kit_type text,
  kit_slots integer,
  kit_discount_type text,
  kit_discount_value numeric,
  preparation_days integer default 1 not null,
  check (sale_mode in ('normal','quote_only')),
  check (preparation_days >= 1)
);
alter table public.products enable row level security;
-- Existing production policy permits all commands; restrictive guards must win.
create policy "Admin pode tudo" on public.products for all using(true);
grant select,insert,update,delete on public.products to anon,authenticated;
grant usage on sequence public.products_id_seq to anon,authenticated;
